spring:
  profiles:
    active: dev  
#    datasource:
#     url: jdbc:mysql://localhost:3306/user_service
#     username: root
#     password: 12345678
#     driver-class-name: com.mysql.cj.jdbc.Driver

# server:
#   port: 10080

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

