spring:
  application:
    name: Configuration-Server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/naba93980/Microservices-Spring-Cloud.git
          search-paths: HotelRatingSystemConfigData
          default-label: config

server:
  port: 8888

